### ISSUE TITLE
webjar-locator does not work on Weblogic 12C

### ISSUE THREAD

**Issue by bjfr** [webjars/webjars-locator#101]
Weblogic 12C has a strange classloader schema, it prefixes jars in WEB-INF/lib with "zip:" instead of "jar:file:".

I have made an UrlProtocolHandler which fixes this, you are more than welcome to fork the code at https://github.com/r2m/webjars-locator-weblogic.

I am not sure exactly what other versions of Weblogic uses the "zip:" prefix in it's classloaders, if anyone knows I can add exakt versions to the documentation.

The project uses Gradle, but it is very small and can easily be translated to Maven if preferred!

**Comment by jamesward** [comment]
Fantastic!  Thanks!

Do you want me to fork this and rename the groupId to `org.webjars` and release it on Maven Central?  Totally up to you.

**Comment by bjfr** [comment]
Yes please do, it will be easier to find for other users if it is available in your repo! Go ahead and rename the groupid and also feel free to rename the packagename to org.webjars if you want!

**Comment by bjfr** [comment]
@jamesward Let me know if I can assist you in any way to fork the code or to test the forked codebase! And if you are having any problems, please let me know and I will do my best to help!

**Comment by jamesward** [comment]
@bjfr I've forked this and I'm working on getting it released.  Quick question: What license do you want to use?

**Comment by bjfr** [comment]
@jamesward MIT license is fine!

**Comment by jamesward** [comment]
Here is the fork: https://github.com/webjars/webjars-locator-weblogic

I'm going to try a release now.

**Comment by jamesward** [comment]
This should be deployed on Maven Central shortly.  Can you test?
```
groupId: org.webjars
artifactId: webjars-locator-weblogic
version: 0.9
```

If there are any issues can you file them on the new repo?

Thanks!

**Comment by bjfr** [comment]
@jamesward Nice, I will test it against my local Weblogic server! Will let you know how it works out ;)
