### ISSUE TITLE
Issues with Spring Boot, Jersey, and Tomcat

### ISSUE THREAD

**Issue by jessemillar** [webjars/webjars-locator#105]
I'm trying to get [`swagger-ui`](https://github.com/webjars/swagger-ui) working in a version agnostic manner inside of Spring Boot with Jersey and Tomcat. According to the [WebJars documentation](https://www.webjars.org/documentation#springboot), having a `pom.xml` similar to the following should allow me to access `swagger-ui` via http://localhost:8080/webjars/swagger-ui/ but it only works via http://localhost:8080/webjars/swagger-ui/3.6.1.
```
<dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jersey</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>swagger-ui</artifactId>
      <version>3.6.1</version>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>webjars-locator</artifactId>
      <version>0.32-1</version>
    </dependency>
</dependencies>
```
Is there anything special I'd need to do to get `webjars-locator` working in this situation?

**Comment by jamesward** [comment]
I'm not sure why but you also need:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```
Here is a sample that demonstrates this:
https://github.com/jamesward/sample-spring_boot

**Comment by jessemillar** [comment]
Is it perhaps because `spring-boot-starter-web` uses `spring-webmvc` where `spring-boot-starter-jersey` does not? It appears that `spring-boot-starter-web` and `spring-boot-starter-jersey` cannot be used simultaneously which implies that those of us using Jersey/JAX-RS are out of luck when it comes to `webjars-locator`...

**Comment by jamesward** [comment]
Perhaps the Spring Boot team can do whatever magic in `spring-boot-starter-jersey` that they do in `spring-boot-starter-web` but you'll need to work with them on that.
