### ISSUE TITLE
webjars-locator not working for requirejs-i18n

### ISSUE THREAD

**Issue by seanmcelroy1971** [webjars/webjars-locator#106]
I have a project that uses the requirejs-i18n webjar but it is not being picked up by the webjars-locator. 

I have examined the generated RequireJS config and while the config has a webjars.version for i18n, it does not have a requirejs.config statement for i18n.

I have managed to work around the bug by creating my own RequireJS config, like this
`
require.config({
paths: {
        "i18n": webjars.path("requirejs-i18n", "i18n")
    }
});
`

**Comment by jamesward** [comment]
So strangely this library didn't have a `bower.json` for the `2.0.4` version:
https://github.com/requirejs/i18n/tree/2.0.4

Which means we can't get the requirejs config.  I'm releasing version `2.0.6` for this which will hopefully resolve the issue since it has a `bower.json` file.

**Comment by seanmcelroy1971** [comment]
It works now. Thanks
