### ISSUE TITLE
Jackson-databind issues with 2.9.4

### ISSUE THREAD

**Issue by ratherDashing** [webjars/webjars-locator#110]
Please see:

https://nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Afasterxml%3Ajackson-databind%3A2.9.4

Is there a way you can update to the latest version 2.9.8?

**Comment by jamesward** [comment]
Thanks for the heads up.  This will be released as `0.35` shortly.
