### ISSUE TITLE
Jackson Core Conflict in Maven

### ISSUE THREAD

**Issue by ratherDashing** [webjars/webjars-locator#111]
Currently this depends on webjars-locator-core .35 which has a dependency on jackson-core 2.7.3.  It also depends on jackson databind 2.9.8 which has a dependency on jackson-core 2.9.8 which maven will ignore due to the multiple dependency.  This causes various incompatibilities what I can solve on my end with exclusions but might be best sorted here.

**Comment by jamesward** [comment]
I've released `0.36` which should fix this.
