### ISSUE TITLE
Doesn't work on JBoss

### ISSUE THREAD

**Issue by mwanji** [webjars/webjars-locator#18]
Tested by deploying [this application](https://github.com/mwanji/wro4j-webjar-versions) to JBoss 7.1

WebJarAssetLocator.getAssetPaths() tests URL protocols for "file" and "jar", but on JBoss the protocol is "vfs", so no assets are found.

**Comment by chevdor** [comment]
I am facing the same issue on Wildfly 9.0.1 and I reported it in #91

**Comment by jamesward** [comment]
@chevdor Does the solution from @mwanji above work for you?

**Comment by chevdor** [comment]
I need to test

**Comment by chevdor** [comment]
Yep, the solution from @mwanji does fix the issue for me with Wildfly 9.0.1
I would add that although I deploy an EAR, the protocol is vfs and not vfszip as discussed in #19 

So in the end, #19 was not merged ?

**Comment by jamesward** [comment]
It looks like #45 replaced #19.

**Comment by mwanji** [comment]
@chevdor You can use https://github.com/mwanji/webjars-locator-jboss-vfs, which uses the ServiceLoader mechanism implemented in #45 . Unfortunately, it seems I never published this to Maven. Can you check that that JAR solves your problem? In exchange, I'll publish it to Maven so that there's a ready-made solution for everyone. ;)

**Comment by chevdor** [comment]
That sounds like quite a deal :smile: 
I will check that out.

**Comment by jamesward** [comment]
@mwanji Let me know if you want me to fork this to the `webjars` org and release under the `org.webjars` groupId.

**Comment by mwanji** [comment]
@jamesward that would be cool. I don't think I have the release rights for that groupId, though, so you'd have to do it yourself.

**Comment by chevdor** [comment]
That would be nice indeed. I quickly tested the JAR from @mwanji but since the package is not the same, I would have to change the webjars-locator-core to load the extra service in order to test.

It might be easier if @jamesward can publish to maven under org.webjars
I would be then glad to test again on my end to confirm.

**Comment by chevdor** [comment]
OK, just to confirm.
I have forked @mwanji repo (https://github.com/chevdor/webjars-locator-jboss-vfs).
I renamed the package and tested using a JAR in Wildfly 9.0.1. I hope @mwanji is OK with that. @mwanji, if not, please just let me know.
It worked right away like a charm.

**Comment by mwanji** [comment]
Thanks for testing it, I'm glad it worked. Why did you need to rename it?

**Comment by chevdor** [comment]
Without renaming, I would have had to modify the webjars-core lib so that
the service loader picks up as well classes from another package
specifically.

2015-12-03 11:35 GMT+01:00 Moandji Ezana <notifications@github.com>:

> Thanks for testing it, I'm glad it worked. Why did you need to rename it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/webjars-locator/issues/18#issuecomment-161590769>
> .
>



-- 
-             chevdor@gmail.com               -
------------------------------------------------------

**Comment by spariev** [comment]
@jamesward any chance publishing this to maven in the near future ? Or should I use @chevdor renamed package for now ? I have the same issue with Wildfly 9.0.2.

**Comment by chevdor** [comment]
Hi @spariev 

The good news for you is that the renamed package works so at least you have a one solution. 
Be careful however, it brings with it an ancient transitive dependency (0.19 if I remember) that will cause you troubles. Make sure to use a recent version of the webjar-locator-core jar. @jamesward published 0.30 to maven central not too long ago. I am using that and it works fine.

I :+1: your request, I would also be happy to take that one directly from maven.
In the meantime, I over you a lazy package attached below :smile: 

central.[webjars-locator-jboss-vfs-0.2.0-SNAPSHOT.jar](https://files.zenhub.io/56718dbe2d5d1a8f7314ea31)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jamesward** [comment]
I've forked the repo: https://github.com/webjars/webjars-locator-jboss-vfs

I cleaned up a few things to get it ready for release: https://github.com/webjars/webjars-locator-jboss-vfs/commit/abe6dbff0c573c620eb5cdfd239e0b34ff1ec188

Someone want to take a look at that and give a :+1: before I release it to Maven Central?

**Comment by mwanji** [comment]
:+1: All the changes seem fairly innocuous.

I'm curious about two things:

1. Why did @chevdor have to rename a package? Isn't the declaration in `META-INF/services/org.webjars.urlprotocols.UrlProtocolHandler` enough for a class, regardless of package, to be picked up by webjars-locator-core? (Of course, the new name is better! I'm just surprised it was technically necessary)

2. How does nexus-staging-maven-plugin work? I've tried to use it in the past and couldn't figure it out. @jamesward do you have any good tutorials or resources about it?

**Comment by jamesward** [comment]
2. All I have to do for a release is run: `mvn release:prepare release:perform` and the `nexus-staging-maven-plugin` uploads the artifacts to Maven Central.

**Comment by chevdor** [comment]
Hey @mwanji, it is because of this line:
https://github.com/webjars/webjars-locator-core/blob/master/src/main/java/org/webjars/WebJarAssetLocator.java#L86

@jamesward checking out now

**Comment by chevdor** [comment]
Yep, look ok to me. Give a heads up once it is in central and I will switch.

**Comment by jamesward** [comment]
Thanks @chevdor & @mwanji! I've released version `0.1.0` to Maven Central.  So I'm going to close this.  Lets move further conversation around this to the new repo: https://github.com/webjars/webjars-locator-jboss-vfs

**Comment by spariev** [comment]
Holy cow, that was quick! @jamesward , @mwanji , @chevdor you guys rock!
Installed webjars-locator-jboss-vfs and it works like a charm, thanks a lot.

**Comment by jamesward** [comment]
:+1:

**Comment by chevdor** [comment]
I did not do much on that one. @mwanji did the work and @jamesward wrapped it up in no time. It is fun 'working' like that guys :+1: Thanks for the good spirit!
