### ISSUE TITLE
Fix behaviour on Java 11

### ISSUE THREAD

**Issue by dwijnand** [webjars/webjars-locator#2]
In https://github.com/webjars/webjars-play/pull/91 we found that webjars-play doesn't work as expected on Java 11.  Debugging I've found that the problem seems to lie in webjars-locator's code, and I was able to back that up by witnessing its unit tests fail on Java 11.

**Comment by dwijnand** [comment]
Oh... (1 minute later) so Marcos has sought to address this with https://github.com/webjars/webjars-locator-core/pull/34.  Perhaps this issue is null and void, but it's unclear yet.

**Comment by jamesward** [comment]
I'm releasing 0.38 with the latest core.  Will update webjars-play shortly.
