### ISSUE TITLE
vulnerability in maven central but not in the repo

### ISSUE THREAD

**Issue by corlaez** [webjars/webjars-locator#68]
jackson-core has a vulerability in the lastest release published to maven central. Is this repo abandoned? Should that be announced? Or did we forgot to publish/automatic publishing is not working?

I personally don't even need this lib, I just pulled it by mistake insteadod of webjars-locator-core and foung out about the vulnerability.

I am not claiming that this code is actually affected by the vulnerability but I find it interesting that the repo is so far ahead any published artifacts.

This is the latest version I can see in maven central and is affected by a vulnerability.
https://mvnrepository.com/artifact/org.webjars/webjars-locator/0.46

**Comment by jamesward** [comment]
I'm releasing `0.47` now which I think should address this.  We don't have automatic publishing for this library.  But that'd be nice to have.
