### ISSUE TITLE
RequireJS support adds unwanted dependencies

### ISSUE THREAD

**Issue by mwanji** [webjars/webjars-locator#70]
The RequireJS class drags in 3 Jackson JARs. I find it annoying that such a small library is adding a whole JSON library.

My biases here are that I don't like Jackson and I don't use RequireJS. From what I could gather, the RequireJS support is used at runtime. Would it be possible to extract it into its own artifact so that those who don't want the dependencies don't get them?

**Comment by jamesward** [comment]
Yeah, we should do this.  How about a structure like:
* webjars-locator-core
* webjars-locator-requirejs
* webjars-locator (depends on core & requirejs for backwards compat)

**Comment by mwanji** [comment]
Cool, that way no clients get broken
