### ISSUE TITLE
RequireJS: dependencies should be defined as packages

### ISSUE THREAD

**Issue by tobice** [webjars/webjars-locator#71]
I've been using this locator to generate the setup Javascript for my WebJar dependencies (`
org.webjars.RequireJS.getSetupJavaScript()`). This approach hower doesn't work for all WebJars. Those that use inner `require()` calls to load more files (like `when` for example) fail to load as by default all paths are resolved using the base path (the `require()` paths are relative to the base path, not to the path of the file they are used in). The only way to fix this is to define `when` dependency as a RequireJS package.

So instead of this:
`requirejs.config({"paths":{"when":["/webjars/when-node/3.5.2/when","when"]}})`

The loading script should generate this:
```
requirejs.config({
  packages: [
    { name: 'when', location: '/webjars/when-node/3.5.2/when', main: 'when' }
  ]
});
```

For more info check my [StackOverflow question and answer](http://stackoverflow.com/questions/28399014/require-js-looking-in-the-wrong-path-for-the-nested-dependencies/28565185).

**Comment by jamesward** [comment]
There are two parts to this...  First we need to update the WebJar's RequireJS config:
https://github.com/webjars/when/commit/bca999445ce634a57c1291be44c813ca9c4ac9be

The second part will be updating `webjars-locator` to replace the location path.  I'll start working on that piece next.

**Comment by jamesward** [comment]
Can you try `webjars-locator` version `0.21` along with `when-node` version `3.5.2-2` and see if that works?

**Comment by tobice** [comment]
It's getting close but it's not working yet. The package path should point to the directory, not to the file itself. The current version of the locator generates the package path as `/webjars/when-node/3.5.2/when` so to get it working the `/when` part should be stripped (if you check my answer on StackOverflow you can see I'm doing exactly that).

Btw. would it be that wrong to include every webjar as a package? I'm not very familiar with RequireJS but as far as I understand it, including any existing webjar as a package shouldn't prevent it from working and on the other hand, it should fix any current or future package that uses inner `require()` calls like `when` does.

**Comment by jamesward** [comment]
Thanks for trying it. We can't auto-generate the `packages` config because we don't know enough info about the libraries.

I'm releasing `when-node` version `3.5.2-3` to try and workaround the `location` problem.  Let me know if that works.  If so, I can fix `webjars-locator` to auto-insert the `location`.

**Comment by tobice** [comment]
I'll try it tomorrow and let you know.

Btw. what might break if you included all webjars as `packages`? As far as I know the only difference is that the paths in local `require` calls are relative to the package position. Which means (as I already mentioned) that it can't break any library that works at this moment and it can only fix those that don't. Or am I wrong? Is there more into it?

**Comment by tobice** [comment]
Okay, `when-node 3.5.2-3` is working.

**Comment by alecharp** [comment]
I think this is the same issue with `angular`, `react` and many other where the `main` (or `index.js`) file is only doing 
```
require('./<PLACE MODULE NAME HERE>');
module.exports = PLACE_MODULE_NAME_HERE;
```

So in the end, the RequireJS configuration is not usable for those projects.. to bad, I was really enjoying not having to do it ;)

**Comment by jamesward** [comment]
Here is the change we made to `when-node` to make it work:
https://github.com/webjars/when/blob/master/node/pom.xml#L23-L29

Want to send PRs to other WebJars that have the same problem?

**Comment by alecharp** [comment]
I'll do it asap

**Comment by alecharp** [comment]
@iamandrewluca I don't recall any context for this, I'm sorry. I guess that I did a PR to the library repository I was using with the code provided in @jamesward comment.

**Comment by iamandrewluca** [comment]
I am using `org.webjars.npm.angular` and generated `RequireJs` config for this is
```js
requirejs.config({
    "paths": {
        "angular": ["/context/webjars/angular/1.5.8/index"]
    }
});
```
and content of `index.js` is 
```js
require('./angular');
module.exports = angular;
```
Tried to override `paths` for `angular` but did not work  
Also tried to use `packages` for  `RequireJs`  config, but no chance

**Comment by jamesward** [comment]
This gets generated by: https://github.com/webjars/webjars-locator/blob/master/src/main/java/org/webjars/RequireJS.java#L258

So I think we'd have to port the changes we made above over there.  Any takers?

**Comment by iamandrewluca** [comment]
Do you mean we have to add `packages` in generated config?
Where can we provide info about packages, if webjar does not provide that?

**Comment by jamesward** [comment]
For `org.webjars.npm` we don't put the RequireJS config in the `pom.xml` we instead generate it via `webjars-locator`.
