### ISSUE TITLE
Documentation for Spring MVC is misleading

### ISSUE THREAD

**Issue by philippn** [webjars/webjars-locator#74]
The documentation reads:

> This RequestMapping returns the setup code for your webjars and requirejs.
> It has to be included in your template before any JavaScript library that uses 
> RequireJS like this:
```
<script data-main="/js/core.js" src="/webjarsjs"></script>
```
> This loads the WebJars RequireJS configuration from webjars-locator and the 
> RequireJS with a main JavaScript of js/app. 

I had tons of fun trying to get this working. In the end, this code in the template worked

		<script src="/webjarsjs" type="text/javascript"></script>
		<script data-main="js/app" src="/webjarslocator/requirejs/require.min.js" type="text/javascript"></script>

Note that the path /webjarslocator/requirejs/require.min.js is mapped using Spring MVC

	@ResponseBody
	@RequestMapping(value="/webjarslocator/{webjar}/{partialPath:.+}", method=RequestMethod.GET)
	public ResponseEntity<Resource> locateWebjarAsset(@PathVariable String webjar, @PathVariable String partialPath) {
		try {
			String fullPath = assetLocator.getFullPath(webjar, partialPath);
			return new ResponseEntity<Resource>(
					new ClassPathResource(fullPath), HttpStatus.OK);
		} catch (Exception e) {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}

Obviously, for simplicity you may rely on a CDN instead in order to load requirejs.

**Comment by philippn** [comment]
To clarify, I'm referring to http://www.webjars.org/documentation#springmvc

**Comment by jamesward** [comment]
Can you send a PR for the doc updates you'd like to see?

**Comment by philippn** [comment]
Sure, here it is: https://github.com/webjars/webjars/pull/878
Hope the wording and format are about right.

**Comment by jamesward** [comment]
Thanks!
