### ISSUE TITLE
Doesn't work with dependencies of individual WebJar like font-awesome

### ISSUE THREAD

**Issue by robross0606** [webjars/webjars-locator#76]
font-awesome webjar has a CSS file which references other resources at URL such as:

     ../fonts/fontawesome-webfont.eot?v=4.3.0'

When referencing font-awesome.css through webjar-locator, the resulting path of this reference would be:

     http://localhost/webjarlocator/fonts/fontawesome-webfont.eot?v=4.3.0

This breaks because "fonts" is not the JAR name and, hence, the dependency cannot be met.

**Comment by robross0606** [comment]
This works fine as long as you change the mechanism for picking up the "restOfUrl" from your examples.  The issue occurs when the path to the css or js file is searched for directly from the "root" of the webjar.  If you specify the subdirectories (which requires a change to the "restOfUrl" search mechanism) then the relative pathing for other dependencies is fine.  The provided examples are misleading.

**Comment by jamesward** [comment]
Not sure what to do about this.  Do you have any suggestions?

**Comment by robross0606** [comment]
For starters, provide more meaningful examples of edge cases.  When referencing a URL, the best idea seems to be to ONLY eliminate the "version" portion of the path and still include every portion of the path beyond the version.  So, instead of this:
     /webjars-locator/font-awesome/font-awesome.css
do this:
     /webjars-locator/font-awesome/css/font-awesome.css
This will result in a more specific match which includes the "/css" directory so then subsequent relative pathing will also work.

The use of "deep searching" is neat, but surely breaks relative dependencies if they exist.

**Comment by jamesward** [comment]
Since I'm not very familiar with how you are using WebJars or the font-awesome library, it would be great if you could add some more useful stuff to the docs: https://github.com/webjars/webjars/blob/master/app/views/documentation.scala.html

**Comment by mwanji** [comment]
It took me a while to figure out that you were using the Spring MVC "version agnostic" support.

The documentation's example actually explicitly demonstrates your usecase, with bootstrap: `<link rel='stylesheet' href='/webjarslocator/bootstrap/css/bootstrap.min.css'>`

It is true, however, that the requirement to keep the entire path except the version should be made explicit.

**Comment by robross0606** [comment]
The example in there does not work with h the annotated example handler.
It will not match the request mapping because of the regex.

**Comment by mwanji** [comment]
Wasn't that fixed following your question on SO? The current documentation doesn't use a regex: `@RequestMapping("/webjarslocator/{webjar}/**")`

**Comment by robross0606** [comment]
Sorry, I haven't reviewed the website in the last 48 hours.  If that was 
fixed, then that's good.

------ Original Message ------

**Comment by anandchakru** [comment]
This worked with latest font-awesome

     <link rel="stylesheet" href="/webjars/font-awesome/css/all.css" />

..


		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>font-awesome</artifactId>
			<version>5.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>webjars-locator</artifactId>
		</dependency>

..


	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
	</parent>
..

        <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
