### ISSUE TITLE
Support npm and bower webjars?

### ISSUE THREAD

**Issue by bertvh** [webjars/webjars-locator#80]
You have this line

```public static final String WEBJARS_MAVEN_PREFIX = "META-INF/maven/org.webjars";```

This prevents npm and bower generated webjars to be picked up because they have a "org.webjars.npm" and "org.webjars.bower" prefix.

I did notice that they often (or never) don't contain the correct dependencies. Nevertheless, just adding both prefixes would already be very useful in my opinion.

**Comment by jamesward** [comment]
That prefix is for the file path in the WebJar which should be `META-INF/maven/org.webjars` for Classic, Bower, and NPM WebJars.

Are you getting an error that we can troubleshoot?

**Comment by bertvh** [comment]
I'm testing with this webjar: "org.webjars**.npm**" % "angular-pouchdb" % "2.0.8"

In the `getRawWebJarRequireJsConfig()`, this line is called (I've expanded the fileName argument) and it does not find the pom.

```RequireJS.class.getClassLoader().getResourceAsStream(META-INF/maven/org.webjars/angular-pouchdb/pom.xml); // returns null```

If I alter the prefix to include **.npm*, it does find  the pom.

```RequireJS.class.getClassLoader().getResourceAsStream("META-INF/maven/org.webjars.npm/angular-pouchdb/pom.xml"); ``` // ok

There is nog error, just a log message:

*Could not read WebJar RequireJS config for: angular-pouchdb 2.0.8
Please file a bug at: http://github.com/webjars/angular-pouchdb/issues/new*

**Comment by jamesward** [comment]
Ah.  Thanks for the explanation.  I need to add handling for NPM WebJars to the RequireJS functionality.  Only Classic WebJars should need to get the `pom.xml` file.

I'll get this done shortly.

**Comment by jamesward** [comment]
This will be released shortly as `0.23`.  Let me know if you have any problems.

**Comment by bertvh** [comment]
Great! Will do.
