### ISSUE TITLE
Cannot resolve path for module-name with a dot

### ISSUE THREAD

**Issue by bertvh** [webjars/webjars-locator#85]
Example case: 

I include this webjar: org.webjars.npm / validate.js / 0.8.0

This is generated by getSetupJavaScript:
`requirejs.config({"paths":{"validate.js":["/transportinspectie/webjars/validate.js/0.8.0/validate"]}})`

Which seems fine but... The problem is that requirejs strips the **.js** to determine the module id. When doing a path lookup, it hence searches for **validate** and not **validate.js**. Since it doesn't find this, the path is ignored.

Probably "validate.js" is not a very good name for the module, but I can't change anything about that. Do you see any harm in making webjars-locator do the same normalization as requirejs?

**Comment by jamesward** [comment]
Should be pretty easy to just change `.` to `-` for the module id.  WDYT?

**Comment by bertvh** [comment]
That is easy, but than I would have to define/build the webjar myself instead of having it generated from npm by webjars.org.

Of course that's just me being lazy ;)

**Comment by jamesward** [comment]
For the NPM WebJars the RequireJS config is auto-generated by this library.  So all we need to do is fix that in this library and then you upgrade and it should be all fixed.

**Comment by jamesward** [comment]
Here is a PR to fix this: https://github.com/webjars/webjars-locator/pull/86

Let me know what you think.

**Comment by bertvh** [comment]
I took a few hours to try out the fix. Had to do the same rename for the versions-array otherwise requirejs keeps looking for 'validate.js' while it is now called 'validate-js' in the require path overrides. See 0399c21aa7fbd9f7f552e0c194dcda7da68e39c3.

With that fix, the correct script tag is generated. 

`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="validate" src="[correct]"></script>`

However, next to the correct tag, there is another tag inserted:

`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="validate" src="[incorrect]"></script>`

I have no idea where the latter comes from. This is something on the requirejs side since all generated by the webjars-locator are now 'validate-js'. Ik have been debugging requirejs but really can't find my way in it. 

I will propably build an alternative webjar for validate.js for now since this is really blocking me. Still available to discuss of course.

**Comment by jamesward** [comment]
Hmmm.  The `versions` array shouldn't be used...  How are you loading require, your config, and the main?

**Comment by jamesward** [comment]
I've tested this in a Play app and it is working:
https://github.com/webjars/sample-play2/tree/test/require-dash-fix

Setup:
https://github.com/webjars/sample-play2/blob/test/require-dash-fix/app/views/index.scala.html#L8-L11

Require:
https://github.com/webjars/sample-play2/blob/test/require-dash-fix/app/assets/javascripts/index.coffee

**Comment by bertvh** [comment]
Omg! My mistake. I had a stray reference to 'validate' in one of our modules (`define(['validate'])`). Just didn't think of looking there. Sometimes I could really hit myself. Instead I'll take a few minutes to meditate ;)

Will check if your base solution (without my versions array change) works.

**Comment by bertvh** [comment]
Ok, your fix works as is. Thanks for the effort and apologies for my mistake.

**Comment by jamesward** [comment]
I'm releasing `0.27` with this fix right now.
