### ISSUE TITLE
getWebJarRequireJSConfigFromMainConfig fails ungracefully on missing JSON attributes

### ISSUE THREAD

**Issue by asazernik** [webjars/webjars-locator#88]
The lines that look like `if (jsonNode.get("main").getNodeType() == foo` throw a `NullPointerException` on a missing "main" attribute. The catch statements below this try block do a reasonable thing on some other exceptions (warn, and return a null config for this WebJar), but this exception is not caught.

**Comment by jamesward** [comment]
Thanks for the report.  Care to submit a failing test and fix in a Pull Request?

**Comment by asazernik** [comment]
Sure - kind of in crunch time right now, but I'll put it on my list for the weekend :-)

**Comment by asazernik** [comment]
Random question - does webjars-locator guarantee support for JDKs below version 7? Or can I use Java 7+ features?

**Comment by jamesward** [comment]
We have a minimum of JDK 7 for this lib:
https://github.com/webjars/webjars-locator/blob/master/pom.xml#L131-L132
