### ISSUE TITLE
Unable to get full path of asset at root path that has multiple matches in a webjar

### ISSUE THREAD

**Issue by jochenberger** [webjars/webjars-locator#90]
Consider the following Groovy script:
```groovy
@Grab(group='org.webjars', module='webjars-locator-core', version='0.28') 
@Grab(group='org.webjars.npm', module='babel-core', version='6.0.16', transitive=false)
import org.webjars.WebJarAssetLocator

def locator = new WebJarAssetLocator()
locator.listAssets().findAll{it.endsWith('browser.js')}.each {
  println "Found asset $it"
}

def fullPath = locator.getFullPath('/browser.js')
```
The output is:
```
Found asset META-INF/resources/webjars/babel-core/6.0.16/browser.js
Found asset META-INF/resources/webjars/babel-core/6.0.16/lib/api/browser.js
Found asset META-INF/resources/webjars/babel-core/6.0.16/lib/api/register/browser.js
Caught: org.webjars.MultipleMatchesException: Multiple matches found for browser.js. Please provide a more specific path, for example by including a version number.
org.webjars.MultipleMatchesException: Multiple matches found for browser.js. Please provide a more specific path, for example by including a version number.
	at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:241)
	at org.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:189)
	at org.webjars.WebJarAssetLocator$getFullPath$0.call(Unknown Source)
	at asset-locator.run(asset-locator.groovy:10)
```
I'd like to be able to get the full path of the `browser.js` file but without having to specify the Webjar's version.

**Comment by jamesward** [comment]
Can you try:

    locator.getFullPath('babel-core', 'browser.js')

I think that method does what you want but probably needs some docs.

BTW, there is a separate repo for `webjars-locator-core`: https://github.com/webjars/webjars-locator-core

**Comment by jochenberger** [comment]
`locator.getFullPath('babel-core', 'browser.js')` behaves just the same because the different `browser.js` files are inside the same webjar.
And I noticed that I should have created the issue in -core, but there's no way to move it apparently. Should I create a new issue there?

**Comment by jamesward** [comment]
I've just released `0.29` which adds a new method that should do what you need:

    locator.getFullPathExact('babel-core', 'browser.js')

Here is the change: https://github.com/webjars/webjars-locator-core/commit/86069b88d14b88757c2be51ee86d4899cbd96310

Feel free to open a new issue on https://github.com/webjars/webjars-locator-core if this doesn't work for you.

**Comment by jochenberger** [comment]
Thanks, I think I'll be able to solve my problem with that change, however that might require me to change the semantics of the webjars "paths" a bit.
Originally, this issue occurred during the usage of https://github.com/eddyson-de/tapestry-webjars. I don't know if you're familiar with Tapestry, but that library provides an integration with Webjars, allowing you to reference assets using an abstract "asset path" (e.g. `webjars:jquery.js` or `webjars:babel-core:browser.js`). Currently, the part after the last colon is passed to `locator.getFullPath`.
Of course, I could change it so that if the last part starts with a slash, it is passed to `getFullPathExact`, but that would be different from the semantics that `getFullPath` uses (ignoring the leading slash).
I could also introduce a special syntax (e.g. `webjars:!browser.js`) but I'd rather like to mirror the resolution behavior of the `getFullPath` method.
My favorite option would be supporting paths like `webjars:$version/browser.js`. I could probably do that for `webjars:babel-core:$version/browser.js`, because I could resolve `$version` if I know the webjar and pass that to `getFullPath` but it will probably be some work for `webjars:$version/browser.js`. The trivial solution would be iterating over all Webjars and trying to find a match, but I'd like to avoid that.
Would you be willing to add support for using something like `$version` in the argument to `getFullPath`? Or do you even have a better solution? Depending on your answer, I can create new issues and maybe even a PR in `-core`.

**Comment by jamesward** [comment]
I see.  Thanks for the details.  You can get the version from an `artifactId`:

    String maybeVersion = webJarAssetLocator.getWebJars().get("foo");

That will be `null` if a WebJar with the specified `artifactId` is not on the classpath.

Let me know if that helps get you where you'd like to go.

**Comment by jochenberger** [comment]
Yes, that helps as long as I know the artifactId of the module that the file is in. I added support for the  `$version` placeholder in my library: https://github.com/eddyson-de/tapestry-webjars/commit/dc272943d2d39321c1507449c9c9926c15a45747#diff-03a4df1a582a69c71772ea7f03672ae4. Seems to work fine so far. I might be able to optimize that a bit by transforming `$version/foo` into an exact search for `/foo`. Thanks for your help.

**Comment by jamesward** [comment]
No problem.  Glad you were able to get this working.
