### ISSUE TITLE
Exception Multiple matches when trying to access resources in the root of a webjar

### ISSUE THREAD

**Issue by chevdor** [webjars/webjars-locator#92]
I am testing a paper element:
```<link rel="import" href="/ProcessStarter/webjarslocator/github-com-polymerelements-paper-button/paper-button.html"/>```

webjars-locator throws an exception due to the fact that it finds several paper-button.html files in the webjar.
Indeed, there is /paper-button.html and /test/paper-button.html. The interesting one is /paper-button.html

I could specify (theoretically) that I want the test version by using 
```<link rel="import" href="/ProcessStarter/webjarslocator/github-com-polymerelements-paper-button/test/paper-button.html"/>```
Doing so, the exception is not thrown but the ```/test/paper-button.html``` file is not the one that is needed.

How can I use the ```/paper-button.html``` that is not in ```/test``` without webjars-locator to be confused?

I naively tested the following without success:
```<link rel="import" href="/ProcessStarter/webjarslocator/github-com-polymerelements-paper-button//paper-button.html"/>```

**Comment by jamesward** [comment]
Can you use the `getFullPathExact` method instead?  See: https://github.com/webjars/webjars-locator-core#obtain-the-full-path-of-an-asset

**Comment by chevdor** [comment]
I confirm the option from @jamesward.
Using getFullPathExact does the trick.
