### ISSUE TITLE
Publish org.webjars:webjars-locator:0.30 to maven central

### ISSUE THREAD

**Issue by TheConstructor** [webjars/webjars-locator#93]
Currently the most recent version on maven central seems to be org.webjars:webjars-locator:0.28 which depends on org.webjars:webjars-locator-core:0.27 (!). Maven central reports the presents of org.webjars:webjars-locator-core:0.30, but you need to pull it explicitly to be able to e.g. use the fix in #65.

Please publish a version of org.webjars:webjars-locator to maven central which automatically uses org.webjars:webjars-locator-core:0.30 thereby reducing the count of explicit dependencies in projects using webjars.

**Comment by jamesward** [comment]
This will be released shortly as `0.29`.
