### ISSUE TITLE
Validate.js is being included in JAR

### ISSUE THREAD

**Issue by eltimn** [webjars/webjars-locator#95]
When I use webjars-locator in a project, the validate.js webjar is also included in my JAR as the scope is not set in the pom.

Is this intended?

**Comment by jamesward** [comment]
I'm not sure what you mean.  Can you provide more details?

**Comment by eltimn** [comment]
The webjars-locator project has a dependency on [validate.js](https://github.com/webjars/webjars-locator/blob/master/pom.xml#L118). If I create a project that depends on webjars-locator, the validate.js JAR will be included in my JAR because of that dependency.

I don't see why a Java library would need a dependency on some JavaScript code, which is why I was wondering if that was intential, or was that meant to be restricted to the test scope?

**Comment by jamesward** [comment]
Ah.  Whoops.  That is definitely a mistake.  Here is the commit that caused this: https://github.com/webjars/webjars-locator/commit/df07ba3ad86495bf999aea06601ff1dfcb839733

I'll get this fixed and get a new release asap.

**Comment by jamesward** [comment]
Version `0.30` will be released shortly.  Thanks for reporting the issue!
