### ISSUE TITLE
webjars-locator not working after Jboss EAP 7.4.15 update (linked to exsiting regression in ClassGraph)

### ISSUE THREAD

**Issue by mainsys-bme** [webjars/webjars-locator#96]
Hello, 

We did notice after latest Jboss 7.4.15 update that our agnostic webjar link were not working anymore.
After some digging we identified it was cause by ClassGraph only scanning /tmp/vfs directories and not the base deployment.
Which cause the issue in 7.4.15 when they stopped duplicating content in /tmp/vfs folders.

I already provided information on the subject to ClassGraph (see https://github.com/classgraph/classgraph/issues/701)

From our testing regression in ClassGraph causing this behavior stater in 4.8.144, current dependency in webjar-locator-core is 4.8.149

Kind regards

**Comment by jamesward** [comment]
Thanks for reporting this.  Someone a while back created this:
https://github.com/webjars/webjars-locator-jboss-vfs

I don't know if that'd resolve your issue though.

Another option might be to use the new locator which doesn't depend on ClassGraph:
https://github.com/webjars/webjars-locator-lite

Let me know if either of those alternatives fix this.  If not, I'll dig deeper.

**Comment by mainsys-bme** [comment]
Thank you for your reply, 
webjars-locator-jboss-vfs is not really an option because it relies on older version of webjars-locator-core including some vulnerable dependencies.

For the moment we have settle to rely on the last know working version of classgraph (4.8.143) and see if the issue can be identified.

I will also give a shot to webjars-locator-lite if I can and keep you updated.

**Comment by jamesward** [comment]
Cool.  Let me know if bumping dependencies in `webjars-locator-jboss-vfs` would help.

**Comment by mainsys-bme** [comment]
Hello @jamesward 
Sorry I had little time to investigate this issue past weeks.
The webjars-locator-jboss-vfs does not work with more recent version of webjars-locator-core.
I didn't manage to understand how to use your streamlined version either sorry.

But there was a new version of classgraph (4.8.168) that address the issue. I could successfully make webjars-locator fail with the 4.8.167 in classpath and success with the 4.8.168 so a bump of this dependency should resolve the issue.

**Comment by jamesward** [comment]
I've released `webjars-locator-core` `0.57` with the bump and will soon release a new `webjars-locator` with the new `webjars-locator-core`.

**Comment by jamesward** [comment]
`webjars-locator` `0.51` will be released shortly.  Let me know if these version bumps don't resolve your issue.

**Comment by mkurz** [comment]
Seems there was a problem releasing?
https://github.com/webjars/webjars-locator-core/issues/146

**Comment by mainsys-bme** [comment]
Hello @jamesward,

I checked and it appears the bump did not occur in 0.57 of locator core but it seems it is on main branch now.
https://github.com/webjars/webjars-locator-core/blob/webjars-locator-core-0.57/pom.xml
https://github.com/webjars/webjars-locator-core/blob/main/pom.xml

**Comment by jamesward** [comment]
The corrected `webjars-locator-core` is being released as `0.58` which should have these changes.  I'll do another `webjars-locator` release soon with the bump.

**Comment by jamesward** [comment]
`webjars-locator` `0.52` is being released now with the `webjars-locator-core` bump.

**Comment by mainsys-bme** [comment]
Thank you @jamesward 
I just tested out the 0.52 and issue seems to be resolved with the bump of dependency.
