### ISSUE TITLE
Maven dependency conflict: commons-lang3

### ISSUE THREAD

**Issue by jedvardsson** [webjars/webjars-locator#97]
There is a problem with the project's maven dependency management. webjars-locator-core dependecy on commons-lang3:3.1 while webjars-locator depends on3:3.4. 

[WARNING]
Dependency convergence error for org.apache.commons:commons-lang3:3.1 paths to dependency are:
+-com.tdc.configurito:configurito-builder:1.0.0-SNAPSHOT
  +-org.webjars:webjars-locator:0.30
    +-org.webjars:webjars-locator-core:0.30
      +-org.apache.commons:commons-lang3:3.1
and
+-com.tdc.configurito:configurito-builder:1.0.0-SNAPSHOT
  +-org.webjars:webjars-locator:0.30
    +-org.apache.commons:commons-lang3:3.4

Solution use mavens dependencyManagement or use maven properties defined in a parent pom like in spring-boot-dependencies which is pulled in by the spring-boot-parent.

**Comment by jamesward** [comment]
Released as `0.31`.  Let me know how it goes.
