### ISSUE TITLE
Missing main entry in package.json not really an error

### ISSUE THREAD

**Issue by alecharp** [webjars/webjars-locator#98]
After I created PRs for NPM project about missing `main` entry in their `package.json`, I was told that this is not an error: https://github.com/sindresorhus/object-assign/pull/33#issuecomment-227081840. It seems that NPM fallback to `index.js` when the `main` entry is missing. 

So I'm wondering if we could just change https://github.com/webjars/webjars-locator/blob/master/src/main/java/org/webjars/RequireJS.java#L411-L413 to reflect is in `webjars-locator`? 

Thank you.

**Comment by jamesward** [comment]
Fixed by #99
